version: '3'
services:
  minio:
    image: "minio/minio:RELEASE.2019-09-11T19-53-16Z"
    command: server /data
    env_file:
      - minio.env
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
