version: '3.7'
services:
  minio:
    image: "minio/minio:RELEASE.2019-09-11T19-53-16Z"
    command: server /data
    env_file:
      - minio.env
    ports:
      - "9000:9000"
    volumes:
      - data-volume:/data
    networks:
      example_net:
        ipv4_address: 172.28.1.1

  sighting_producer:
    image: "skillmill/sb-big-data-meetup:local"
    command: foo
    env_file:
      - minio.env
      - producer.env
    volumes:
      - data-volume:/data
    networks:
      example_net:
        ipv4_address: 172.28.1.2

volumes:
  data-volume:

networks:
  example_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
