version: '3.7'
services:
  minio:
    image: "minio/minio:RELEASE.2019-09-11T19-53-16Z"
    env_file:
      - .env
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    networks:
      example_net:
        ipv4_address: 172.28.1.1

  sighting_producer:
    image: "skillmill/sb-big-data-meetup:latest"
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: java -jar /srv/producer.jar
    networks:
      example_net:
        ipv4_address: 172.28.1.2

#  sighting_producer2:
#    image: "skillmill/sb-big-data-meetup:latest"
#    env_file:
#      - .env
#    environment:
#      - INTERVAL_MILLIS=100
#    depends_on:
#      - minio
#    entrypoint: java -jar /srv/producer.jar
#    networks:
#      example_net:
#        ipv4_address: 172.28.1.3

networks:
  example_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
