version: '3.7'
services:
  minio:
    image: "minio/minio:RELEASE.2019-09-11T19-53-16Z"
    command: server /data
    env_file:
      - minio.env
    ports:
      - "9000:9000"
    volumes:
      - data-volume:/data
    networks:
      example_net:
        ipv4_address: 172.28.1.1

  sighting_producer:
    image: "skillmill/sb-big-data-meetup:local"
    command: foo
    env_file:
      - minio.env
      - producer.env
    volumes:
      - data-volume:/data
    networks:
      example_net:
        ipv4_address: 172.28.1.2

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minio_access_key minio_secret_key;
      /usr/bin/mc rm -r --force minio/example-bucket;
      /usr/bin/mc mb minio/somebucketname;
      /usr/bin/mc policy download minio/example-bucket;
      exit 0;
      "
    env_file:
      - minio.env
volumes:
  data-volume:

networks:
  example_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
